// Generated by CoffeeScript 1.3.3
(function() {

  window.classes.Enemies = (function() {

    function Enemies(context, players) {
      this.context = context;
      this.players = players;
      this.collection = [];
    }

    Enemies.prototype.add = function() {
      return this.collection.push(new window.classes.Enemy(this.context, this));
    };

    Enemies.prototype.remove = function(enemy) {
      return this.collection.splice(this.collection.indexOf(enemy), 1);
    };

    Enemies.prototype.animate = function() {
      var enemy, player, _i, _j, _len, _len1, _ref, _ref1;
      _ref = this.players;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        player = _ref[_i];
        _ref1 = this.collection;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          enemy = _ref1[_j];
          enemy.animate();
          if (utils.intersect(player, enemy)) {
            utils.fight(player, enemy);
          }
        }
      }
      if (this.collection.length < 10) {
        return this.add();
      }
    };

    return Enemies;

  })();

}).call(this);
